# Generated by Django 5.0.2 on 2024-03-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_card_holder_alter_profile_billing_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cvv_code',
            new_name='cvc',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='term',
            new_name='expiry',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='billing_address',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='card_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_holder',
        ),
    ]
