# Generated by Django 5.0.2 on 2024-03-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_cvv_code_profile_cvc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
