# Generated by Django 5.0.2 on 2024-03-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_name_alter_profile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiry',
            field=models.CharField(default='', max_length=7),
        ),
    ]
