# Generated by Django 5.0.2 on 2024-03-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_dressstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dress_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.dressstyle'),
        ),
    ]
