# Generated by Django 5.0.2 on 2024-03-03 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_dress_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dress_style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.dressstyle'),
        ),
    ]
